using Backend.Data;
using Microsoft.EntityFrameworkCore;

namespace Backend.Services;

/// <summary>
/// 在已有的 Oracle 数据卷中补齐论坛治理新增的表。这样即使 Docker 没有重建数据库，
/// “敏感词库”接口也不会因为表不存在而前端空白或 500。
/// </summary>
public static class ForumGovernanceSchemaInitializer
{
    public static async Task EnsureAsync(IServiceProvider services, ILogger logger)
    {
        try
        {
            using var scope = services.CreateScope();
            var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();

            const string ensureSensitiveWordTable = """
                DECLARE
                    v_exists NUMBER;
                BEGIN
                    SELECT COUNT(*) INTO v_exists
                    FROM USER_TABLES
                    WHERE TABLE_NAME = 'PostSensitiveWord';

                    IF v_exists = 0 THEN
                        EXECUTE IMMEDIATE 'CREATE TABLE "PostSensitiveWord" (
                            "id" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                            "word" VARCHAR2(200) NOT NULL,
                            "createTime" TIMESTAMP,
                            CONSTRAINT "PK_PostSensitiveWord" PRIMARY KEY ("id")
                        )';
                    END IF;
                END;
                """;

            await db.Database.ExecuteSqlRawAsync(ensureSensitiveWordTable);

            // 旧数据卷可能在 targetType 加入前就已初始化。没有该列时，
            // 含敏感词的内容会先写入 PendingReview，随后写审核记录失败，造成“内容被隐藏但审核队列为空”。
            const string ensureAuditRecordTargetType = """
                DECLARE
                    v_exists NUMBER;
                BEGIN
                    SELECT COUNT(*) INTO v_exists
                    FROM USER_TAB_COLUMNS
                    WHERE TABLE_NAME = 'AuditRecord'
                      AND COLUMN_NAME = 'targetType';

                    IF v_exists = 0 THEN
                        EXECUTE IMMEDIATE 'ALTER TABLE "AuditRecord" ADD ("targetType" VARCHAR2(50) DEFAULT ''Post'')';
                    END IF;
                END;
                """;
            await db.Database.ExecuteSqlRawAsync(ensureAuditRecordTargetType);
            await db.Database.ExecuteSqlRawAsync("""
                UPDATE "AuditRecord"
                SET "targetType" = 'Post'
                WHERE "targetType" IS NULL
                """);

            // 修复旧版本已经留下的“待审核但没有审核记录”内容。
            // 这些内容是旧库缺少 targetType 时，帖子/评论先保存成功而审核记录保存失败造成的。
            await db.Database.ExecuteSqlRawAsync("""
                INSERT INTO "AuditRecord" ("targetType", "targetId", "triggerWord", "status", "createTime")
                SELECT 'Post', p."postId", '历史待审核内容', 'Pending', COALESCE(p."updateTime", p."createTime")
                FROM "Post" p
                WHERE p."status" = 'PendingReview'
                  AND NOT EXISTS (
                      SELECT 1
                      FROM "AuditRecord" a
                      WHERE a."targetType" = 'Post'
                        AND a."targetId" = p."postId"
                        AND a."status" = 'Pending'
                  )
                """);
            await db.Database.ExecuteSqlRawAsync("""
                INSERT INTO "AuditRecord" ("targetType", "targetId", "triggerWord", "status", "createTime")
                SELECT 'Comment', c."commentId", '历史待审核内容', 'Pending', c."createTime"
                FROM "PostComment" c
                WHERE c."status" = 'PendingReview'
                  AND NOT EXISTS (
                      SELECT 1
                      FROM "AuditRecord" a
                      WHERE a."targetType" = 'Comment'
                        AND a."targetId" = c."commentId"
                        AND a."status" = 'Pending'
                  )
                """);
            await db.Database.ExecuteSqlRawAsync("COMMIT");

            // 早期种子脚本曾创建过未加引号的 POSTSENSITIVEWORD，启动时无损迁移其中的词。
            const string migrateLegacySensitiveWords = """
                DECLARE
                    v_legacy NUMBER;
                BEGIN
                    SELECT COUNT(*) INTO v_legacy
                    FROM USER_TABLES
                    WHERE TABLE_NAME = 'POSTSENSITIVEWORD';

                    IF v_legacy > 0 THEN
                        EXECUTE IMMEDIATE 'INSERT INTO "PostSensitiveWord" ("word", "createTime")
                            SELECT legacy.WORD, legacy.CREATETIME
                            FROM POSTSENSITIVEWORD legacy
                            WHERE legacy.WORD IS NOT NULL
                              AND NOT EXISTS (
                                  SELECT 1 FROM "PostSensitiveWord" target
                                  WHERE LOWER(target."word") = LOWER(legacy.WORD)
                              )';
                    END IF;
                END;
                """;
            await db.Database.ExecuteSqlRawAsync(migrateLegacySensitiveWords);

            var existingWords = await db.PostSensitiveWords
                .Where(w => w.Word != null)
                .Select(w => w.Word!)
                .ToListAsync();
            var created = false;
            foreach (var word in new[] { "违禁", "敏感词", "spam" })
            {
                if (existingWords.Any(existing => string.Equals(existing, word, StringComparison.OrdinalIgnoreCase)))
                    continue;

                db.PostSensitiveWords.Add(new Backend.Models.PostSensitiveWord
                {
                    Word = word,
                    CreateTime = DateTime.Now
                });
                created = true;
            }

            if (created)
                await db.SaveChangesAsync();

        }
        catch (Exception ex)
        {
            // 不能因为可选的治理表初始化失败阻断整个站点；控制器会返回清晰的数据库错误。
            logger.LogWarning(ex, "论坛治理表初始化失败。请执行 database/05_forum_marketplace_extensions.sql。");
        }
    }
}
