-- ============================================================
-- 01_schema.sql
-- Oracle 18c 数据库表结构、主键、外键与检查约束
-- 驼峰命名 + 双引号包裹
-- ============================================================

-- 切换到 appuser 用户执行
ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = APPUSER;

-- 第一步：建所有主表（无外键依赖）
-- ============================================================

CREATE TABLE "User" (
    "userId"       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "username"     VARCHAR2(50),
    "email"        VARCHAR2(100),
    "passwordHash" VARCHAR2(255),
    "userCode"     VARCHAR2(50),
    "contact"      VARCHAR2(100),
    "bio"          VARCHAR2(500),
    "credit"       NUMBER,
    "status"       VARCHAR2(20),
    "sessionVersion" VARCHAR2(64),
    CONSTRAINT "PK_User" PRIMARY KEY ("userId")
);

CREATE TABLE "Role" (
    "roleId"      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "roleName"    VARCHAR2(50),
    "description" VARCHAR2(200),
    "createTime"  TIMESTAMP,
    CONSTRAINT "PK_Role" PRIMARY KEY ("roleId")
);

CREATE TABLE "Permission" (
    "permissionId"   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "permissionName" VARCHAR2(100),
    "description"    VARCHAR2(200),
    "resource"       VARCHAR2(50),
    "action"         VARCHAR2(50),
    CONSTRAINT "PK_Permission" PRIMARY KEY ("permissionId")
);

CREATE TABLE "EmailCode" (
    "emailCodeId" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "email"       VARCHAR2(100),
    "code"        VARCHAR2(10),
    "purpose"     VARCHAR2(30),
    "sendTime"    TIMESTAMP,
    "expireTime"  TIMESTAMP,
    "isUsed"      CHAR(1),
    CONSTRAINT "PK_EmailCode" PRIMARY KEY ("emailCodeId")
);

CREATE TABLE "PostSensitiveWord" (
    "id"         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "word"       VARCHAR2(200) NOT NULL,
    "createTime" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "PK_PostSensitiveWord" PRIMARY KEY ("id"),
    CONSTRAINT "UQ_PostSensitiveWord_Word" UNIQUE ("word")
);

CREATE TABLE "ProductCategory" (
    "categoryId"   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "categoryName" VARCHAR2(50) NOT NULL,
    "description"  VARCHAR2(200),
    "displayOrder" NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT "PK_ProductCategory" PRIMARY KEY ("categoryId"),
    CONSTRAINT "UQ_ProductCategory_Name" UNIQUE ("categoryName")
);

CREATE TABLE "ProductCondition" (
    "conditionId"   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "conditionName" VARCHAR2(50) NOT NULL,
    "description"   VARCHAR2(200),
    "displayOrder"  NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT "PK_ProductCondition" PRIMARY KEY ("conditionId"),
    CONSTRAINT "UQ_ProductCondition_Name" UNIQUE ("conditionName")
);

-- 第二步：建依赖 User 的表
-- ============================================================

CREATE TABLE "Wallet" (
    "walletId"    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "balance"     NUMBER,
    "userId"      NUMBER,
    CONSTRAINT "PK_Wallet" PRIMARY KEY ("walletId"),
    CONSTRAINT "FK_Wallet_User" FOREIGN KEY ("userId") REFERENCES "User"("userId")
);

CREATE TABLE "MediaFile" (
    "mediaId"          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "storageProvider"  VARCHAR2(50) DEFAULT 's3' NOT NULL,
    "objectKey"        VARCHAR2(500),
    "fileName"         VARCHAR2(4000),
    "originalFileName" VARCHAR2(4000),
    "url"              VARCHAR2(500) NOT NULL,
    "mimeType"         VARCHAR2(100),
    "sizeBytes"        NUMBER,
    "contentHash"      VARCHAR2(64),
    "uploadTime"       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "uploadedByUserId" NUMBER,
    CONSTRAINT "PK_MediaFile" PRIMARY KEY ("mediaId"),
    CONSTRAINT "FK_MediaFile_User" FOREIGN KEY ("uploadedByUserId") REFERENCES "User"("userId")
);

CREATE TABLE "UserAvatar" (
    "userId"  NUMBER NOT NULL,
    "mediaId" NUMBER NOT NULL,
    CONSTRAINT "PK_UserAvatar" PRIMARY KEY ("userId"),
    CONSTRAINT "UQ_UserAvatar_Media" UNIQUE ("mediaId"),
    CONSTRAINT "FK_UserAvatar_User" FOREIGN KEY ("userId") REFERENCES "User"("userId"),
    CONSTRAINT "FK_UserAvatar_Media" FOREIGN KEY ("mediaId") REFERENCES "MediaFile"("mediaId")
);

CREATE TABLE "Forum" (
    "forumId"     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "forumName"   VARCHAR2(100),
    "description" VARCHAR2(500),
    "status"      VARCHAR2(20),
    "createTime"  TIMESTAMP,
    "creatorId"   NUMBER,
    CONSTRAINT "PK_Forum" PRIMARY KEY ("forumId"),
    CONSTRAINT "FK_Forum_User" FOREIGN KEY ("creatorId") REFERENCES "User"("userId")
);

CREATE TABLE "ForumAvatar" (
    "forumId" NUMBER NOT NULL,
    "mediaId" NUMBER NOT NULL,
    CONSTRAINT "PK_ForumAvatar" PRIMARY KEY ("forumId"),
    CONSTRAINT "FK_ForumAvatar_Forum" FOREIGN KEY ("forumId") REFERENCES "Forum"("forumId"),
    CONSTRAINT "FK_ForumAvatar_Media" FOREIGN KEY ("mediaId") REFERENCES "MediaFile"("mediaId")
);

CREATE TABLE "UserRole" (
    "userId"     NUMBER NOT NULL,
    "roleId"     NUMBER NOT NULL,
    "assignTime" TIMESTAMP,
    CONSTRAINT "PK_UserRole" PRIMARY KEY ("userId", "roleId"),
    CONSTRAINT "FK_UserRole_User" FOREIGN KEY ("userId") REFERENCES "User"("userId"),
    CONSTRAINT "FK_UserRole_Role" FOREIGN KEY ("roleId") REFERENCES "Role"("roleId")
);

CREATE TABLE "RolePermission" (
    "roleId"       NUMBER NOT NULL,
    "permissionId" NUMBER NOT NULL,
    CONSTRAINT "PK_RolePermission" PRIMARY KEY ("roleId", "permissionId"),
    CONSTRAINT "FK_RolePermission_Role" FOREIGN KEY ("roleId") REFERENCES "Role"("roleId"),
    CONSTRAINT "FK_RolePermission_Permission" FOREIGN KEY ("permissionId") REFERENCES "Permission"("permissionId")
);

CREATE TABLE "FriendShip" (
    "friendshipId" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "userId"       NUMBER NOT NULL,
    "friendId"     NUMBER NOT NULL,
    "status"       VARCHAR2(20) DEFAULT 'Pending' NOT NULL,
    "createTime"   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updateTime"   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "PK_FriendShip" PRIMARY KEY ("friendshipId"),
    CONSTRAINT "CK_FriendShip_NotSelf" CHECK ("userId" <> "friendId"),
    CONSTRAINT "CK_FriendShip_Status" CHECK ("status" IN ('Pending', 'Accepted', 'Rejected')),
    CONSTRAINT "FK_FriendShip_User"   FOREIGN KEY ("userId")   REFERENCES "User"("userId"),
    CONSTRAINT "FK_FriendShip_Friend" FOREIGN KEY ("friendId") REFERENCES "User"("userId")
);

CREATE TABLE "CreditAdjustment" (
    "creditAdjustmentId" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "userId"             NUMBER,
    "description"        VARCHAR2(500),
    "changePoints"       NUMBER,
    "beforeCredit"       NUMBER,
    "afterCredit"        NUMBER,
    "operatorId"         NUMBER,
    "adjustTime"         TIMESTAMP,
    CONSTRAINT "PK_CreditAdjustment" PRIMARY KEY ("creditAdjustmentId"),
    CONSTRAINT "FK_CreditAdj_User" FOREIGN KEY ("userId") REFERENCES "User"("userId"),
    CONSTRAINT "FK_CreditAdj_Operator" FOREIGN KEY ("operatorId") REFERENCES "User"("userId")
);

CREATE TABLE "FavoriteFolder" (
    "folderId"   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "folderName" VARCHAR2(100),
    "createTime" TIMESTAMP,
    "userId"     NUMBER,
    CONSTRAINT "PK_FavoriteFolder" PRIMARY KEY ("folderId"),
    CONSTRAINT "FK_FavFolder_User" FOREIGN KEY ("userId") REFERENCES "User"("userId")
);

CREATE TABLE "Product" (
    "productId"   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "title"       VARCHAR2(200),
    "description" VARCHAR2(4000),
    "categoryId"  NUMBER NOT NULL,
    "conditionId" NUMBER NOT NULL,
    "price"       NUMBER,
    "stock"       NUMBER,
    "status"      VARCHAR2(20),
    "publishTime" TIMESTAMP,
    "userId"      NUMBER,
    CONSTRAINT "PK_Product" PRIMARY KEY ("productId"),
    CONSTRAINT "FK_Product_User" FOREIGN KEY ("userId") REFERENCES "User"("userId"),
    CONSTRAINT "FK_Product_Category" FOREIGN KEY ("categoryId") REFERENCES "ProductCategory"("categoryId"),
    CONSTRAINT "FK_Product_Condition" FOREIGN KEY ("conditionId") REFERENCES "ProductCondition"("conditionId")
);

CREATE TABLE "AuditRecord" (
    "auditId"     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "targetType"  VARCHAR2(50) DEFAULT 'Post',
    "targetId"    NUMBER,
    "triggerWord" VARCHAR2(200),
    "status"      VARCHAR2(20),
    "createTime"  TIMESTAMP,
    "auditorId"   NUMBER,
    CONSTRAINT "PK_AuditRecord" PRIMARY KEY ("auditId"),
    CONSTRAINT "FK_AuditRecord_User" FOREIGN KEY ("auditorId") REFERENCES "User"("userId")
);

CREATE TABLE "PrivateMessage" (
    "messageId"  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "content"    VARCHAR2(4000) NOT NULL,
    "sendTime"   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "isRead"     CHAR(1) DEFAULT '0' NOT NULL,
    "receiverId" NUMBER NOT NULL,
    "senderId"   NUMBER NOT NULL,
    CONSTRAINT "PK_PrivateMessage" PRIMARY KEY ("messageId"),
    CONSTRAINT "CK_PrivateMessage_NotSelf" CHECK ("senderId" <> "receiverId"),
    CONSTRAINT "CK_PrivateMessage_IsRead" CHECK ("isRead" IN ('0', '1')),
    CONSTRAINT "FK_PrvMsg_Receiver" FOREIGN KEY ("receiverId") REFERENCES "User"("userId"),
    CONSTRAINT "FK_PrvMsg_Sender"   FOREIGN KEY ("senderId")   REFERENCES "User"("userId")
);

-- 第三步：建依赖 Forum 的表
-- ============================================================

CREATE TABLE "Post" (
    "postId"     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "title"      VARCHAR2(200),
    "content"    CLOB,
    "likeCount"  NUMBER,
    "viewCount"  NUMBER,
    "createTime" TIMESTAMP,
    "updateTime" TIMESTAMP,
    "status"     VARCHAR2(20),
    "userId"     NUMBER,
    "forumId"    NUMBER,
    CONSTRAINT "PK_Post" PRIMARY KEY ("postId"),
    CONSTRAINT "FK_Post_User"  FOREIGN KEY ("userId")  REFERENCES "User"("userId"),
    CONSTRAINT "FK_Post_Forum" FOREIGN KEY ("forumId") REFERENCES "Forum"("forumId")
);

CREATE TABLE "PostMedia" (
    "postId"       NUMBER NOT NULL,
    "mediaId"      NUMBER NOT NULL,
    "displayOrder" NUMBER NOT NULL,
    CONSTRAINT "PK_PostMedia" PRIMARY KEY ("postId", "mediaId"),
    CONSTRAINT "UQ_PostMedia_Order" UNIQUE ("postId", "displayOrder"),
    CONSTRAINT "FK_PostMedia_Post" FOREIGN KEY ("postId") REFERENCES "Post"("postId"),
    CONSTRAINT "FK_PostMedia_Media" FOREIGN KEY ("mediaId") REFERENCES "MediaFile"("mediaId")
);

CREATE TABLE "ForumManager" (
    "forumId" NUMBER NOT NULL,
    "userId"  NUMBER NOT NULL,
    "role"    VARCHAR2(20) DEFAULT 'Moderator' NOT NULL,
    CONSTRAINT "PK_ForumManager" PRIMARY KEY ("forumId", "userId"),
    CONSTRAINT "FK_ForumMgr_Forum" FOREIGN KEY ("forumId") REFERENCES "Forum"("forumId"),
    CONSTRAINT "FK_ForumMgr_User"  FOREIGN KEY ("userId")  REFERENCES "User"("userId"),
    CONSTRAINT "CK_ForumMgr_Role" CHECK ("role" IN ('Moderator', 'Admin'))
);

CREATE TABLE "ForumMember" (
    "forumId"  NUMBER NOT NULL,
    "userId"   NUMBER NOT NULL,
    "joinTime" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "PK_ForumMember" PRIMARY KEY ("forumId", "userId"),
    CONSTRAINT "FK_ForumMember_Forum" FOREIGN KEY ("forumId") REFERENCES "Forum"("forumId") ON DELETE CASCADE,
    CONSTRAINT "FK_ForumMember_User"  FOREIGN KEY ("userId")  REFERENCES "User"("userId")
);

-- 第四步：建依赖 Post 的表
-- ============================================================

CREATE TABLE "PostComment" (
    "commentId"       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "content"         VARCHAR2(4000),
    "status"          VARCHAR2(20),
    "createTime"      TIMESTAMP,
    "postId"          NUMBER,
    "userId"          NUMBER,
    "parentCommentId" NUMBER,
    CONSTRAINT "PK_PostComment" PRIMARY KEY ("commentId"),
    CONSTRAINT "FK_PostCmt_Post"          FOREIGN KEY ("postId")          REFERENCES "Post"("postId"),
    CONSTRAINT "FK_PostCmt_User"          FOREIGN KEY ("userId")          REFERENCES "User"("userId"),
    CONSTRAINT "FK_PostCmt_ParentComment" FOREIGN KEY ("parentCommentId") REFERENCES "PostComment"("commentId")
);

CREATE TABLE "PostLike" (
    "likeId"     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "postId"     NUMBER,
    "userId"     NUMBER,
    "createTime" TIMESTAMP,
    CONSTRAINT "PK_PostLike" PRIMARY KEY ("likeId"),
    CONSTRAINT "FK_PostLike_Post" FOREIGN KEY ("postId") REFERENCES "Post"("postId"),
    CONSTRAINT "FK_PostLike_User" FOREIGN KEY ("userId") REFERENCES "User"("userId")
);

CREATE TABLE "FolderPost" (
    "postId"   NUMBER NOT NULL,
    "folderId" NUMBER NOT NULL,
    CONSTRAINT "PK_FolderPost" PRIMARY KEY ("folderId", "postId"),
    CONSTRAINT "FK_FolderPost_Post"   FOREIGN KEY ("postId")   REFERENCES "Post"("postId"),
    CONSTRAINT "FK_FolderPost_Folder" FOREIGN KEY ("folderId") REFERENCES "FavoriteFolder"("folderId")
);

-- 第五步：建依赖 Product 的表
-- ============================================================

CREATE TABLE "ProductMedia" (
    "productId"    NUMBER NOT NULL,
    "mediaId"      NUMBER NOT NULL,
    "displayOrder" NUMBER NOT NULL,
    CONSTRAINT "PK_ProductMedia" PRIMARY KEY ("productId", "mediaId"),
    CONSTRAINT "UQ_ProductMedia_Order" UNIQUE ("productId", "displayOrder"),
    CONSTRAINT "FK_ProductMedia_Product" FOREIGN KEY ("productId") REFERENCES "Product"("productId"),
    CONSTRAINT "FK_ProductMedia_Media" FOREIGN KEY ("mediaId") REFERENCES "MediaFile"("mediaId")
);

CREATE TABLE "Transaction" (
    "transactionId"     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "transactionAmount" NUMBER,
    "transactionStatus" VARCHAR2(20),
    "createTime"        TIMESTAMP,
    "payTime"           TIMESTAMP,
    "userId"            NUMBER,
    "productId"         NUMBER,
    CONSTRAINT "PK_Transaction" PRIMARY KEY ("transactionId"),
    CONSTRAINT "FK_Trans_User"    FOREIGN KEY ("userId")    REFERENCES "User"("userId"),
    CONSTRAINT "FK_Trans_Product" FOREIGN KEY ("productId") REFERENCES "Product"("productId")
);

CREATE TABLE "OrderMessage" (
    "orderMessageId" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "content"        VARCHAR2(4000) NOT NULL,
    "sendTime"       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "isArchived"     CHAR(1) DEFAULT '0' NOT NULL,
    "transactionId"  NUMBER NOT NULL,
    "senderId"       NUMBER NOT NULL,
    CONSTRAINT "PK_OrderMessage" PRIMARY KEY ("orderMessageId"),
    CONSTRAINT "CK_OrderMessage_Archived" CHECK ("isArchived" IN ('0', '1')),
    CONSTRAINT "FK_OrderMsg_Transaction" FOREIGN KEY ("transactionId") REFERENCES "Transaction"("transactionId"),
    CONSTRAINT "FK_OrderMsg_Sender" FOREIGN KEY ("senderId") REFERENCES "User"("userId")
);

CREATE TABLE "ReportTicket" (
    "reportId"    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "targetType"  VARCHAR2(50) NOT NULL,
    "targetId"    NUMBER NOT NULL,
    "reason"      VARCHAR2(500) NOT NULL,
    "status"      VARCHAR2(20) DEFAULT 'Pending' NOT NULL,
    "createTime"  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "reviewTime"  TIMESTAMP,
    "result"      VARCHAR2(500),
    "reporterId"  NUMBER NOT NULL,
    "reviewerId"  NUMBER,
    CONSTRAINT "PK_ReportTicket" PRIMARY KEY ("reportId"),
    CONSTRAINT "FK_Report_Reporter" FOREIGN KEY ("reporterId") REFERENCES "User"("userId"),
    CONSTRAINT "FK_Report_Reviewer" FOREIGN KEY ("reviewerId") REFERENCES "User"("userId")
);

-- 第六步：建依赖 Transaction 的表
-- ============================================================

CREATE TABLE "DisputeTicket" (
    "ticketId"      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "reason"        VARCHAR2(500),
    "status"        VARCHAR2(20),
    "createTime"    TIMESTAMP,
    "assignTime"    TIMESTAMP,
    "transactionId" NUMBER,
    "userId"        NUMBER,
    "arbitratorId"  NUMBER,
    CONSTRAINT "PK_DisputeTicket" PRIMARY KEY ("ticketId"),
    CONSTRAINT "FK_Dispute_Transaction" FOREIGN KEY ("transactionId") REFERENCES "Transaction"("transactionId"),
    CONSTRAINT "FK_Dispute_User"        FOREIGN KEY ("userId")        REFERENCES "User"("userId"),
    CONSTRAINT "FK_Dispute_Arbitrator"  FOREIGN KEY ("arbitratorId")  REFERENCES "User"("userId")
);

CREATE TABLE "Notification" (
    "notificationId" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "title"          VARCHAR2(200),
    "content"        VARCHAR2(4000),
    "createTime"     TIMESTAMP,
    "type"           VARCHAR2(50) DEFAULT 'System',
    "targetType"     VARCHAR2(50),
    "targetId"       NUMBER,
    "link"           VARCHAR2(500),
    "isRead"         CHAR(1) DEFAULT '0',
    "readTime"       TIMESTAMP,
    "eventKey"       VARCHAR2(200),
    "transactionId"  NUMBER,
    "userId"         NUMBER,
    CONSTRAINT "PK_Notification" PRIMARY KEY ("notificationId"),
    CONSTRAINT "FK_Notif_Transaction" FOREIGN KEY ("transactionId") REFERENCES "Transaction"("transactionId"),
    CONSTRAINT "FK_Notif_User"        FOREIGN KEY ("userId")        REFERENCES "User"("userId")
);

-- 第七步：建依赖 DisputeTicket 和 Wallet 的表
-- ============================================================

CREATE TABLE "ArbitrationResult" (
    "resultId"        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "decision"        VARCHAR2(500),
    "refundAmount"    NUMBER,
    "createTime"      TIMESTAMP,
    "disputeTicketId" NUMBER,
    "walletId"        NUMBER,
    CONSTRAINT "PK_ArbitrationResult" PRIMARY KEY ("resultId"),
    CONSTRAINT "FK_Arb_DisputeTicket" FOREIGN KEY ("disputeTicketId") REFERENCES "DisputeTicket"("ticketId"),
    CONSTRAINT "FK_Arb_Wallet"        FOREIGN KEY ("walletId")        REFERENCES "Wallet"("walletId")
);

COMMIT;
