-- ============================================================
-- 01_tables.sql
-- Oracle 18c 数据库表结构创建脚本
-- 驼峰命名 + 双引号包裹
-- ============================================================

-- 切换到 appuser 用户执行
ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = APPUSER;

-- 第一步：建所有主表（无外键依赖）
-- ============================================================

CREATE TABLE "User" (
    "userId"       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "username"     VARCHAR2(50),
    "email"        VARCHAR2(100),
    "passwordHash" VARCHAR2(255),
    "userCode"     VARCHAR2(50),
    "credit"       NUMBER,
    "status"       VARCHAR2(20),
    "userLevel"    NUMBER DEFAULT 1,
    "totalCredit"  NUMBER DEFAULT 0,
    CONSTRAINT "PK_User" PRIMARY KEY ("userId")
);

CREATE TABLE "Role" (
    "roleId"      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "roleName"    VARCHAR2(50),
    "description" VARCHAR2(200),
    "createTime"  TIMESTAMP,
    CONSTRAINT "PK_Role" PRIMARY KEY ("roleId")
);

CREATE TABLE "Permission" (
    "permissionId"   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "permissionName" VARCHAR2(100),
    "description"    VARCHAR2(200),
    "resource"       VARCHAR2(50),
    "action"         VARCHAR2(50),
    CONSTRAINT "PK_Permission" PRIMARY KEY ("permissionId")
);

CREATE TABLE "EmailCode" (
    "emailCodeId" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "email"       VARCHAR2(100),
    "code"        VARCHAR2(10),
    "sendTime"    TIMESTAMP,
    "expireTime"  TIMESTAMP,
    "isUsed"      CHAR(1),
    CONSTRAINT "PK_EmailCode" PRIMARY KEY ("emailCodeId")
);

CREATE TABLE "PostTag" (
    "tagId"      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "tagName"    VARCHAR2(50),
    "createTime" TIMESTAMP,
    CONSTRAINT "PK_PostTag" PRIMARY KEY ("tagId")
);

-- 第二步：建依赖 User 的表
-- ============================================================

CREATE TABLE "Wallet" (
    "walletId"    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "balance"     NUMBER,
    "payPassword" VARCHAR2(255),
    "userId"      NUMBER,
    CONSTRAINT "PK_Wallet" PRIMARY KEY ("walletId"),
    CONSTRAINT "FK_Wallet_User" FOREIGN KEY ("userId") REFERENCES "User"("userId")
);

CREATE TABLE "Forum" (
    "forumId"     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "forumName"   VARCHAR2(100),
    "description" VARCHAR2(500),
    "status"      VARCHAR2(20),
    "createTime"  TIMESTAMP,
    "creatorId"   NUMBER,
    CONSTRAINT "PK_Forum" PRIMARY KEY ("forumId"),
    CONSTRAINT "FK_Forum_User" FOREIGN KEY ("creatorId") REFERENCES "User"("userId")
);

CREATE TABLE "UserRole" (
    "userId"     NUMBER NOT NULL,
    "roleId"     NUMBER NOT NULL,
    "assignTime" TIMESTAMP,
    CONSTRAINT "PK_UserRole" PRIMARY KEY ("userId", "roleId"),
    CONSTRAINT "FK_UserRole_User" FOREIGN KEY ("userId") REFERENCES "User"("userId"),
    CONSTRAINT "FK_UserRole_Role" FOREIGN KEY ("roleId") REFERENCES "Role"("roleId")
);

CREATE TABLE "RolePermission" (
    "roleId"       NUMBER NOT NULL,
    "permissionId" NUMBER NOT NULL,
    CONSTRAINT "PK_RolePermission" PRIMARY KEY ("roleId", "permissionId"),
    CONSTRAINT "FK_RolePermission_Role" FOREIGN KEY ("roleId") REFERENCES "Role"("roleId"),
    CONSTRAINT "FK_RolePermission_Permission" FOREIGN KEY ("permissionId") REFERENCES "Permission"("permissionId")
);

CREATE TABLE "FriendShip" (
    "friendshipId" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "userId"       NUMBER,
    "friendId"     NUMBER,
    "status"       VARCHAR2(20),
    "createTime"   TIMESTAMP,
    "updateTime"   TIMESTAMP,
    CONSTRAINT "PK_FriendShip" PRIMARY KEY ("friendshipId"),
    CONSTRAINT "FK_FriendShip_User"   FOREIGN KEY ("userId")   REFERENCES "User"("userId"),
    CONSTRAINT "FK_FriendShip_Friend" FOREIGN KEY ("friendId") REFERENCES "User"("userId")
);

CREATE TABLE "CreditAdjustment" (
    "creditAdjustmentId" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "userId"             NUMBER,
    "description"        VARCHAR2(500),
    "changePoints"       NUMBER,
    "adjustTime"         TIMESTAMP,
    CONSTRAINT "PK_CreditAdjustment" PRIMARY KEY ("creditAdjustmentId"),
    CONSTRAINT "FK_CreditAdj_User" FOREIGN KEY ("userId") REFERENCES "User"("userId")
);

CREATE TABLE "FavoriteFolder" (
    "folderId"   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "folderName" VARCHAR2(100),
    "createTime" TIMESTAMP,
    "userId"     NUMBER,
    CONSTRAINT "PK_FavoriteFolder" PRIMARY KEY ("folderId"),
    CONSTRAINT "FK_FavFolder_User" FOREIGN KEY ("userId") REFERENCES "User"("userId")
);

CREATE TABLE "Product" (
    "productId"   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "title"       VARCHAR2(200),
    "description" VARCHAR2(4000),
    "imageUrls"   CLOB,
    "price"       NUMBER,
    "stock"       NUMBER,
    "status"      VARCHAR2(20),
    "publishTime" TIMESTAMP,
    "userId"      NUMBER,
    CONSTRAINT "PK_Product" PRIMARY KEY ("productId"),
    CONSTRAINT "FK_Product_User" FOREIGN KEY ("userId") REFERENCES "User"("userId")
);

CREATE TABLE "AuditRecord" (
    "auditId"     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "targetType"  VARCHAR2(50) DEFAULT 'Post',
    "targetId"    NUMBER,
    "triggerWord" VARCHAR2(200),
    "status"      VARCHAR2(20),
    "createTime"  TIMESTAMP,
    "auditorId"   NUMBER,
    CONSTRAINT "PK_AuditRecord" PRIMARY KEY ("auditId"),
    CONSTRAINT "FK_AuditRecord_User" FOREIGN KEY ("auditorId") REFERENCES "User"("userId")
);

CREATE TABLE "PrivateMessage" (
    "messageId"  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "content"    VARCHAR2(4000),
    "sendTime"   TIMESTAMP,
    "isRead"     CHAR(1),
    "receiverId" NUMBER,
    "senderId"   NUMBER,
    CONSTRAINT "PK_PrivateMessage" PRIMARY KEY ("messageId"),
    CONSTRAINT "FK_PrvMsg_Receiver" FOREIGN KEY ("receiverId") REFERENCES "User"("userId"),
    CONSTRAINT "FK_PrvMsg_Sender"   FOREIGN KEY ("senderId")   REFERENCES "User"("userId")
);

-- 第三步：建依赖 Forum 的表
-- ============================================================

CREATE TABLE "Post" (
    "postId"     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "title"      VARCHAR2(200),
    "content"    CLOB,
    "imageUrls"  CLOB,
    "heatScore"  NUMBER,
    "likeCount"  NUMBER,
    "viewCount"  NUMBER,
    "createTime" TIMESTAMP,
    "updateTime" TIMESTAMP,
    "status"     VARCHAR2(20),
    "userId"     NUMBER,
    "forumId"    NUMBER,
    CONSTRAINT "PK_Post" PRIMARY KEY ("postId"),
    CONSTRAINT "FK_Post_User"  FOREIGN KEY ("userId")  REFERENCES "User"("userId"),
    CONSTRAINT "FK_Post_Forum" FOREIGN KEY ("forumId") REFERENCES "Forum"("forumId")
);

CREATE TABLE "ForumManager" (
    "forumId" NUMBER NOT NULL,
    "userId"  NUMBER NOT NULL,
    CONSTRAINT "PK_ForumManager" PRIMARY KEY ("forumId", "userId"),
    CONSTRAINT "FK_ForumMgr_Forum" FOREIGN KEY ("forumId") REFERENCES "Forum"("forumId"),
    CONSTRAINT "FK_ForumMgr_User"  FOREIGN KEY ("userId")  REFERENCES "User"("userId")
);

-- 第四步：建依赖 Post 的表
-- ============================================================

CREATE TABLE "PostComment" (
    "commentId"       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "content"         VARCHAR2(4000),
    "status"          VARCHAR2(20),
    "createTime"      TIMESTAMP,
    "postId"          NUMBER,
    "userId"          NUMBER,
    "parentCommentId" NUMBER,
    CONSTRAINT "PK_PostComment" PRIMARY KEY ("commentId"),
    CONSTRAINT "FK_PostCmt_Post"          FOREIGN KEY ("postId")          REFERENCES "Post"("postId"),
    CONSTRAINT "FK_PostCmt_User"          FOREIGN KEY ("userId")          REFERENCES "User"("userId"),
    CONSTRAINT "FK_PostCmt_ParentComment" FOREIGN KEY ("parentCommentId") REFERENCES "PostComment"("commentId")
);

CREATE TABLE "PostLike" (
    "likeId"     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "postId"     NUMBER,
    "userId"     NUMBER,
    "createTime" TIMESTAMP,
    CONSTRAINT "PK_PostLike" PRIMARY KEY ("likeId"),
    CONSTRAINT "FK_PostLike_Post" FOREIGN KEY ("postId") REFERENCES "Post"("postId"),
    CONSTRAINT "FK_PostLike_User" FOREIGN KEY ("userId") REFERENCES "User"("userId")
);

CREATE TABLE "TagPost" (
    "postId" NUMBER NOT NULL,
    "tagId"  NUMBER NOT NULL,
    CONSTRAINT "PK_TagPost" PRIMARY KEY ("postId", "tagId"),
    CONSTRAINT "FK_TagPost_Post" FOREIGN KEY ("postId") REFERENCES "Post"("postId"),
    CONSTRAINT "FK_TagPost_Tag"  FOREIGN KEY ("tagId")  REFERENCES "PostTag"("tagId")
);

CREATE TABLE "FolderPost" (
    "postId"   NUMBER NOT NULL,
    "folderId" NUMBER NOT NULL,
    CONSTRAINT "PK_FolderPost" PRIMARY KEY ("folderId", "postId"),
    CONSTRAINT "FK_FolderPost_Post"   FOREIGN KEY ("postId")   REFERENCES "Post"("postId"),
    CONSTRAINT "FK_FolderPost_Folder" FOREIGN KEY ("folderId") REFERENCES "FavoriteFolder"("folderId")
);

-- 第五步：建依赖 Product 的表
-- ============================================================

CREATE TABLE "Transaction" (
    "transactionId"     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "transactionAmount" NUMBER,
    "transactionStatus" VARCHAR2(20),
    "createTime"        TIMESTAMP,
    "payTime"           TIMESTAMP,
    "userId"            NUMBER,
    "productId"         NUMBER,
    CONSTRAINT "PK_Transaction" PRIMARY KEY ("transactionId"),
    CONSTRAINT "FK_Trans_User"    FOREIGN KEY ("userId")    REFERENCES "User"("userId"),
    CONSTRAINT "FK_Trans_Product" FOREIGN KEY ("productId") REFERENCES "Product"("productId")
);

-- 第六步：建依赖 Transaction 的表
-- ============================================================

CREATE TABLE "DisputeTicket" (
    "ticketId"      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "reason"        VARCHAR2(500),
    "status"        VARCHAR2(20),
    "createTime"    TIMESTAMP,
    "assignTime"    TIMESTAMP,
    "transactionId" NUMBER,
    "userId"        NUMBER,
    "arbitratorId"  NUMBER,
    CONSTRAINT "PK_DisputeTicket" PRIMARY KEY ("ticketId"),
    CONSTRAINT "FK_Dispute_Transaction" FOREIGN KEY ("transactionId") REFERENCES "Transaction"("transactionId"),
    CONSTRAINT "FK_Dispute_User"        FOREIGN KEY ("userId")        REFERENCES "User"("userId"),
    CONSTRAINT "FK_Dispute_Arbitrator"  FOREIGN KEY ("arbitratorId")  REFERENCES "User"("userId")
);

CREATE TABLE "Notification" (
    "notificationId" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "title"          VARCHAR2(200),
    "content"        VARCHAR2(4000),
    "createTime"     TIMESTAMP,
    "transactionId"  NUMBER,
    "userId"         NUMBER,
    CONSTRAINT "PK_Notification" PRIMARY KEY ("notificationId"),
    CONSTRAINT "FK_Notif_Transaction" FOREIGN KEY ("transactionId") REFERENCES "Transaction"("transactionId"),
    CONSTRAINT "FK_Notif_User"        FOREIGN KEY ("userId")        REFERENCES "User"("userId")
);

-- 第七步：建依赖 DisputeTicket 和 Wallet 的表
-- ============================================================

CREATE TABLE "ArbitrationResult" (
    "resultId"        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "decision"        VARCHAR2(500),
    "refundAmount"    NUMBER,
    "createTime"      TIMESTAMP,
    "disputeTicketId" NUMBER,
    "walletId"        NUMBER,
    CONSTRAINT "PK_ArbitrationResult" PRIMARY KEY ("resultId"),
    CONSTRAINT "FK_Arb_DisputeTicket" FOREIGN KEY ("disputeTicketId") REFERENCES "DisputeTicket"("ticketId"),
    CONSTRAINT "FK_Arb_Wallet"        FOREIGN KEY ("walletId")        REFERENCES "Wallet"("walletId")
);

COMMIT;
