-- ============================================================
-- 05_forum_marketplace_extensions.sql
-- 论坛与交易扩展表：订单留言板、举报工单
-- ============================================================

ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = APPUSER;

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "DisputeTicket" ADD "arbitratorId" NUMBER';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "DisputeTicket" ADD CONSTRAINT "FK_Dispute_Arbitrator" FOREIGN KEY ("arbitratorId") REFERENCES "User"("userId")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2275 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "Post" ADD "imageUrls" CLOB';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "Product" ADD "imageUrls" CLOB';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "AuditRecord" ADD "targetType" VARCHAR2(50) DEFAULT ''Post''';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
/

UPDATE "AuditRecord"
SET "targetType" = 'Post'
WHERE "targetType" IS NULL;

DELETE FROM "RolePermission"
WHERE "roleId" = (SELECT "roleId" FROM "Role" WHERE "roleName" = 'User')
AND "permissionId" IN (
    SELECT "permissionId"
    FROM "Permission"
    WHERE "permissionName" IN ('posts.edit', 'products.edit')
);

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE "FriendShip" (
            "friendshipId" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
            "userId"       NUMBER,
            "friendId"     NUMBER,
            "status"       VARCHAR2(20),
            "createTime"   TIMESTAMP,
            "updateTime"   TIMESTAMP,
            CONSTRAINT "PK_FriendShip" PRIMARY KEY ("friendshipId"),
            CONSTRAINT "FK_FriendShip_User"   FOREIGN KEY ("userId")   REFERENCES "User"("userId"),
            CONSTRAINT "FK_FriendShip_Friend" FOREIGN KEY ("friendId") REFERENCES "User"("userId")
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE "CreditAdjustment" (
            "creditAdjustmentId" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
            "userId"             NUMBER,
            "description"        VARCHAR2(500),
            "changePoints"       NUMBER,
            "adjustTime"         TIMESTAMP,
            CONSTRAINT "PK_CreditAdjustment" PRIMARY KEY ("creditAdjustmentId"),
            CONSTRAINT "FK_CreditAdj_User" FOREIGN KEY ("userId") REFERENCES "User"("userId")
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE "FavoriteFolder" (
            "folderId"   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
            "folderName" VARCHAR2(100),
            "createTime" TIMESTAMP,
            "userId"     NUMBER,
            CONSTRAINT "PK_FavoriteFolder" PRIMARY KEY ("folderId"),
            CONSTRAINT "FK_FavFolder_User" FOREIGN KEY ("userId") REFERENCES "User"("userId")
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE "ForumManager" (
            "forumId" NUMBER NOT NULL,
            "userId"  NUMBER NOT NULL,
            CONSTRAINT "PK_ForumManager" PRIMARY KEY ("forumId", "userId"),
            CONSTRAINT "FK_ForumMgr_Forum" FOREIGN KEY ("forumId") REFERENCES "Forum"("forumId"),
            CONSTRAINT "FK_ForumMgr_User"  FOREIGN KEY ("userId")  REFERENCES "User"("userId")
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE "PostLike" (
            "likeId"     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
            "postId"     NUMBER,
            "userId"     NUMBER,
            "createTime" TIMESTAMP,
            CONSTRAINT "PK_PostLike" PRIMARY KEY ("likeId"),
            CONSTRAINT "FK_PostLike_Post" FOREIGN KEY ("postId") REFERENCES "Post"("postId"),
            CONSTRAINT "FK_PostLike_User" FOREIGN KEY ("userId") REFERENCES "User"("userId")
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE "TagPost" (
            "postId" NUMBER NOT NULL,
            "tagId"  NUMBER NOT NULL,
            CONSTRAINT "PK_TagPost" PRIMARY KEY ("postId", "tagId"),
            CONSTRAINT "FK_TagPost_Post" FOREIGN KEY ("postId") REFERENCES "Post"("postId"),
            CONSTRAINT "FK_TagPost_Tag"  FOREIGN KEY ("tagId")  REFERENCES "PostTag"("tagId")
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE "FolderPost" (
            "postId"   NUMBER NOT NULL,
            "folderId" NUMBER NOT NULL,
            CONSTRAINT "PK_FolderPost" PRIMARY KEY ("folderId", "postId"),
            CONSTRAINT "FK_FolderPost_Post"   FOREIGN KEY ("postId")   REFERENCES "Post"("postId"),
            CONSTRAINT "FK_FolderPost_Folder" FOREIGN KEY ("folderId") REFERENCES "FavoriteFolder"("folderId")
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE "OrderMessage" (
            "orderMessageId" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
            "content"        VARCHAR2(4000),
            "sendTime"       TIMESTAMP,
            "isArchived"     CHAR(1),
            "transactionId"  NUMBER,
            "senderId"       NUMBER,
            CONSTRAINT "PK_OrderMessage" PRIMARY KEY ("orderMessageId"),
            CONSTRAINT "FK_OrderMsg_Transaction" FOREIGN KEY ("transactionId") REFERENCES "Transaction"("transactionId"),
            CONSTRAINT "FK_OrderMsg_Sender"      FOREIGN KEY ("senderId")      REFERENCES "User"("userId")
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE "ReportTicket" (
            "reportId"    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
            "targetType"  VARCHAR2(50),
            "targetId"    NUMBER,
            "reason"      VARCHAR2(500),
            "status"      VARCHAR2(20),
            "createTime"  TIMESTAMP,
            "reviewTime"  TIMESTAMP,
            "result"      VARCHAR2(500),
            "reporterId"  NUMBER,
            "reviewerId"  NUMBER,
            CONSTRAINT "PK_ReportTicket" PRIMARY KEY ("reportId"),
            CONSTRAINT "FK_Report_Reporter" FOREIGN KEY ("reporterId") REFERENCES "User"("userId"),
            CONSTRAINT "FK_Report_Reviewer" FOREIGN KEY ("reviewerId") REFERENCES "User"("userId")
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX "idx_ordermsg_transaction" ON "OrderMessage"("transactionId", "sendTime")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX "idx_friendship_users" ON "FriendShip"("userId", "friendId", "status")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX "idx_friendship_friend" ON "FriendShip"("friendId", "status")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX "idx_credit_adjust_user" ON "CreditAdjustment"("userId", "adjustTime")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX "idx_favfolder_user" ON "FavoriteFolder"("userId", "createTime")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        DELETE FROM "PostLike" pl
        WHERE pl."likeId" NOT IN (
            SELECT MIN(pl2."likeId")
            FROM "PostLike" pl2
            GROUP BY pl2."postId", pl2."userId"
        )';
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX "idx_postlike_post_user"';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1418 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "idx_postlike_post_user" ON "PostLike"("postId", "userId")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX "idx_folderpost_folder" ON "FolderPost"("folderId", "postId")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX "idx_report_status" ON "ReportTicket"("status", "createTime")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX "idx_report_target" ON "ReportTicket"("targetType", "targetId")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

COMMIT;

-- ============================================================
-- Notification module v1: read state, type, target object, and dedup key
-- ============================================================

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "Notification" ADD "type" VARCHAR2(50) DEFAULT ''System''';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "Notification" ADD "targetType" VARCHAR2(50)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "Notification" ADD "targetId" NUMBER';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "Notification" ADD "link" VARCHAR2(500)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "Notification" ADD "isRead" CHAR(1) DEFAULT ''0''';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "Notification" ADD "readTime" TIMESTAMP';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE "Notification" ADD "eventKey" VARCHAR2(200)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
/

UPDATE "Notification"
SET "type" = 'System'
WHERE "type" IS NULL;

UPDATE "Notification"
SET "isRead" = '0'
WHERE "isRead" IS NULL;

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX "IX_Notification_EventKey" ON "Notification"("eventKey")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/
