-- ============================================================
-- 09_media_file.sql
-- 媒体文件统一存储元数据表
-- ============================================================

ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = APPUSER;

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE "MediaFile" (
            "mediaId" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
            "ownerType" VARCHAR2(30),
            "ownerId" NUMBER,
            "storageProvider" VARCHAR2(50) DEFAULT ''local'',
            "objectKey" VARCHAR2(500),
            "fileName" VARCHAR2(4000),
            "originalFileName" VARCHAR2(4000),
            "url" VARCHAR2(500),
            "mimeType" VARCHAR2(100),
            "sizeBytes" NUMBER,
            "contentHash" VARCHAR2(64),
            "uploadTime" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            "uploadedByUserId" NUMBER,
            "displayOrder" NUMBER,
            CONSTRAINT "PK_MediaFile" PRIMARY KEY ("mediaId"),
            CONSTRAINT "FK_MediaFile_User" FOREIGN KEY ("uploadedByUserId") REFERENCES "User"("userId")
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE INDEX "idx_media_owner" ON "MediaFile" ("ownerType", "ownerId")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE INDEX "idx_media_uploadedby" ON "MediaFile" ("uploadedByUserId")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE INDEX "idx_media_upload_time" ON "MediaFile" ("uploadTime")';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

COMMIT;
